### ISSUE TITLE
Suggerimenti per le affiliation

### ISSUE THREAD

**Issue by robol** [Unipisa/dm-manager#14]
Sarebbe carino avere il typeahead anche per affiliation, per evitare che profilerino versioni diverse delle stesse università (Università di Pisa, Universita' di Pisa, UNIVERSITA DI PISA, ...). Lo farei senza forzare l'esistenza nel database, solo come suggerimento.

**Comment by paolini** [comment]
Comincio a pensare che le affiliation debbano anch'esse avere la propria collection... Si potrebbero mettere diverse informazioni interessanti (città, paese, abbreviazione)
