### ISSUE TITLE
implementare notifiche

### ISSUE THREAD

**Issue by paolini** [Unipisa/dm-manager#44]

**Comment by paolini** [comment]
@robol ora vengono create delle entrate nella collection "notifications" quando vengono create, modificate, o cancellate le visite.

Ti ho assegnato la issue :-) 

ci sarebbe da fare il processo che controlla periodicamente la collection ed invia i messaggi alle persone che hanno ruoli che corrispondono al "channel" della notifica.

**Comment by robol** [comment]
Insieme a @paolini abbiamo implementato una prima versione, chiudo. Manca una seconda parte, che sono le notifiche periodiche (ad es. per la portineria). Apro una issue separata per quello.
