### ISSUE TITLE
notifica portineria per tutte le assegnazioni stanze

### ISSUE THREAD

**Issue by paolini** [Unipisa/dm-manager#51]
Dice @salafrancesco: implementare le notifiche alla portineria in modo che includano il personale

Io direi di notificare tutte le assegnazioni di stanze... viene più semplice e mi pare sensato.

@robol, assegno a te: ma se non hai tempo vedo se posso farlo io.

**Comment by robol** [comment]
L'ho aggiunto, chiudo la issue.
